version: '3'

services:
  cms:
    image: node:18-alpine
    ports:
      - '1337:3000'
    restart: always
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - db_cms
    env_file:
      - .env

  db_cms:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - '5434:5432'
    volumes:
      - data:/data/postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  data:
  node_modules:
